import datetime
print("Exercise 1")
name = input(print("Please enter your name: "))
yourAge = input(print(f"What is your age, {name}?"))
currentDateTime = datetime.datetime.now()
date = currentDateTime.date() 
year = date.strftime("%Y")
print(f"You will be a hundred years old after {100 - int(yourAge)} and it will be {int(year) + 100 - int(yourAge)}.")
print(f"Because now is {year}.")
print("Exercise 2")
print("Please enter the values of parameters below.")
width = input(print("enter width:"))
length = input(print("enter length:"))
height = input(print("enter height:"))
print(f"Your room space is {float(width) * float(length) * float(height)} ")
print("Exercise 3")
celsius = input(print("enter temperature in Celsius: "))
fahrenheit = 32+float(celsius)*(9/5)
print(f"Your temperature is {fahrenheit} in Fahrenheit")
